/// <reference types="react-native-css/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is
// normally generated by NativeWind at Metro-config time; it is committed here instead, with
// `disableTypeScriptGeneration: true` in metro.config.js, so that starting Metro does not
// repeatedly rewrite tsconfig.json (tsconfig's `**/*.ts` already includes this file).
